/**
 * Config exporter: turns an approved ticket into a runnable config for the
 * open-source agent (github repo), plus the terminal steps to run it.
 *
 * Honesty rule: the agent today automates the covered-call family (Income
 * Mode fully; Stay Neutral's call leg - the perp hedge is roadmap). Other
 * strategies export as a captured SPEC with `enabled: false` so nothing
 * pretends to run before the engine supports it.
 */
import { Quote, asset } from "../data/appdata";
import { callDelta } from "./options";
import { VenueMode, VENUES } from "../data/venues";

export const RUNNABLE = new Set(["income", "neutral"]);

export function buildConfigYaml(q: Quote, qty: number, mode: VenueMode): string {
  const a = asset(q.assetSymbol);
  const v = VENUES[mode];
  const leg = q.legs[0];
  const t = q.dte / 365;
  const delta = leg ? callDelta(a.spot, leg.strike, a.iv, t) : 0.25;
  const runnable = RUNNABLE.has(q.strategyId);
  const minYield = Math.max(0.03, q.incomeAnnualPct * 0.5);

  const head = [
    `# Overwrite agent config - generated by overwrite.pro/app`,
    `# Strategy: ${q.title} (${q.strategyId})`,
    `# ${q.headline.replace(/\n/g, " ")}`,
    `# Venue mode at export: ${v.label} (${v.endpoint})`,
    `#`,
    runnable
      ? `# RUNNABLE: the open-source agent automates this strategy's option loop.${q.strategyId === "neutral" ? "\n# NOTE: the perp delta-hedge leg is agent roadmap - run the call leg only,\n# or hedge manually until it ships." : ""}`
      : `# SPEC ONLY: the open-source agent currently automates the covered-call`
        + `\n# family. This file captures your structured trade; wheel/shield/collar/`
        + `\n# short engines are on the agent roadmap - the underlying stays disabled.`,
    `# Numbers are demo pricing - the agent re-prices everything live at start.`,
  ].join("\n");

  const stop = q.stopLossPct != null
    ? `  max_drawdown_pause: "${q.stopLossPct.toFixed(2)}"   # your auto-close: pause + alert at -${(q.stopLossPct * 100).toFixed(0)}%`
    : `  max_drawdown_pause: "0.15"`;

  return `${head}

venue: derive
quote_asset: USDC
cycle_seconds: 900
state_db: data/overwrite.db
log_dir: data/logs
status_export: ""

# SAFE DEFAULT. To trade for real you must BOTH set this false AND pass --live
# (and pass \`preflight\` - the agent refuses --live without a fresh stamp).
dry_run: true

derive:
  environment: test      # v2 testnet today${mode === "v3" ? " · V3 adapter in progress (testnet.api.derive.xyz/v3)" : ""}
  extra_fee: "0"

underlyings:
  - symbol: ${q.assetSymbol}
    enabled: ${runnable}
    max_utilization: "0.90"
    delta_target: "${Math.min(0.45, Math.max(0.1, delta)).toFixed(2)}"   # ≈ your ${leg ? `$${leg.strike.toLocaleString()}` : ""} cap at today's vol
    delta_min: "0.10"
    delta_max: "0.45"
    dte_target: ${q.dte}
    dte_min: ${Math.max(7, Math.min(25, q.dte - 10))}
    dte_max: ${q.dte + 25}
    roll_dte: ${Math.max(5, Math.min(21, q.dte - 14))}
    take_profit_pct: "0.75"
    defensive_delta: "0.60"
    min_annualized_yield: "${minYield.toFixed(2)}"
    max_spread_pct: "0.15"
    min_order: "${a.step >= 100 ? "0.01" : "0.1"}"
    max_order: "${qty}"

risk:
  max_maintenance_usage: "0.40"
  max_orders_per_day: 60
  max_price_dev_from_mark: "0.25"
  max_quote_age_sec: 90
  kill_switch_file: data/KILL
  pause_file: data/PAUSE
${stop}

execution:
  fill_timeout_sec: 45
  max_reprices: 3
  aggression: "0.25"
  post_only: true
  maker_mode: true
`;
}

export function runSteps(q: Quote): { title: string; cmd: string }[] {
  const cfg = `configs/${q.strategyId}-${q.assetSymbol.toLowerCase()}.yaml`;
  return [
    { title: "Get the agent (open source, MIT)",
      cmd: "git clone https://github.com/keegan-dotcom/overwrite && cd overwrite" },
    { title: "Install (Python 3.10-3.13; guided setup)",
      cmd: "./install.sh" },
    { title: "Drop this config in",
      cmd: `mv ~/Downloads/${q.strategyId}-${q.assetSymbol.toLowerCase()}.yaml ${cfg}` },
    { title: "Add your keys to .env, then load them",
      cmd: "cp .env.example .env   # fill DERIVE_WALLET / DERIVE_SESSION_KEY / DERIVE_SUBACCOUNT_ID\nset -a; source .env; set +a" },
    { title: "Preflight - the guided go-live inspection",
      cmd: `python3 -m agent.main preflight --config ${cfg}` },
    { title: "Watch one dry-run cycle (no orders placed)",
      cmd: `python3 -m agent.main once --config ${cfg}` },
    { title: "Go live (testnet first; needs dry_run: false in the YAML)",
      cmd: `python3 -m agent.main run --config ${cfg} --live` },
  ];
}

export function downloadYaml(q: Quote, qty: number, mode: VenueMode): void {
  const blob = new Blob([buildConfigYaml(q, qty, mode)], { type: "text/yaml" });
  const url = URL.createObjectURL(blob);
  const el = document.createElement("a");
  el.href = url;
  el.download = `${q.strategyId}-${q.assetSymbol.toLowerCase()}.yaml`;
  document.body.appendChild(el);
  el.click();
  el.remove();
  URL.revokeObjectURL(url);
}
